# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fmabrouk/Documents/YT/FIR_25KHz_DAC/FIR_25kHz/FIR_25K/FIR_25K.srcs/sources_1/ip/fir_25KHz/fir_25KHz.xci
# IP: The module: 'fir_25KHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_DAC/FIR_25kHz/FIR_25K/FIR_25K.srcs/sources_1/ip/fir_25KHz/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_25KHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_DAC/FIR_25kHz/FIR_25K/FIR_25K.srcs/sources_1/ip/fir_25KHz/fir_25KHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_25KHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/fmabrouk/Documents/YT/FIR_25KHz_DAC/FIR_25kHz/FIR_25K/FIR_25K.srcs/sources_1/ip/fir_25KHz/fir_25KHz.xci
# IP: The module: 'fir_25KHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_DAC/FIR_25kHz/FIR_25K/FIR_25K.srcs/sources_1/ip/fir_25KHz/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_25KHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_DAC/FIR_25kHz/FIR_25K/FIR_25K.srcs/sources_1/ip/fir_25KHz/fir_25KHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_25KHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
