# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/fir_sysgen_clock.xdc

# XDC: imports/sysgen/fir_sysgen.xdc

# Block Designs: bd/fir_sysgen_bd/fir_sysgen_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_sysgen_bd || ORIG_REF_NAME==fir_sysgen_bd} -quiet] -quiet

# IP: bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_bd_fir_sysgen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_sysgen_bd_fir_sysgen_1_0 || ORIG_REF_NAME==fir_sysgen_bd_fir_sysgen_1_0} -quiet] -quiet

# XDC: bd/fir_sysgen_bd/fir_sysgen_bd_ooc.xdc
