# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_bd_fir_sysgen_1_0.xci
# IP: The module: 'fir_sysgen_bd_fir_sysgen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_fir_compiler_v7_2_i0/fir_sysgen_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_sysgen_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_sysgen_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/constrs/fir_sysgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_sysgen_bd_fir_sysgen_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_bd_fir_sysgen_1_0.xci
# IP: The module: 'fir_sysgen_bd_fir_sysgen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_fir_compiler_v7_2_i0/fir_sysgen_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_sysgen_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/fir_sysgen_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_sysgen_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_sysgen_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/YT/FIR_25KHz_SysGen/FIR25KHz_IP/ip_catalog/fir_sysgen.srcs/sources_1/bd/fir_sysgen_bd/ip/fir_sysgen_bd_fir_sysgen_1_0/constrs/fir_sysgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_sysgen_bd_fir_sysgen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
